services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    expose:
      - "3000"
    networks:
      - app_network

  caddy:
    image: caddy:2
    container_name: caddy_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs
    networks:
      - app_network

networks:
  app_network:


volumes:
  caddy_data:
  caddy_config:
